name: deploy
on:
  push:
    branches:
      - main
      - feature/push_images_to_ecr
env:
  AWS_REGION: ap-northeast-1
jobs:
  deploy:
    name: Deploy app to AWS Forgate
    runs-on: ubuntu-latest
